### ISSUE TITLE
数据地址失效

### ISSUE THREAD

**Issue by Nihilitior** [TolicWang/DeepST#3]
您好, 论文数据的百度云与onedrive地址均已失效, 如果您这边留有备份的话, 方便分享一下么

**Comment by TolicWang** [comment]
链接: https://pan.baidu.com/s/1xRNv9GXvJH6WMXTaPtJcpw 提取码: vr9x

**Comment by Nihilitior** [comment]
已收到, 非常感谢

**Comment by njtuzzy** [comment]
@TolicWang 能在分享一下TaxiBJ的数据集吗，上个分享过期了：（ 谢谢

**Comment by Nihilitior** [comment]
> @TolicWang 能在分享一下TaxiBJ的数据集吗，上个分享过期了：（ 谢谢

链接：https://pan.baidu.com/s/1YWN_4SSurAMpPd8LYaSuvA 
提取码：rrzn

**Comment by TolicWang** [comment]
可关注公众号”月来客栈“ 回复 ”DeepST“获取

**Comment by basharathussain** [comment]
Thank you very much for sharing the thesis code. 
WIll you please share the TaxiBJ dataset  and also BJ13_M32x32_T30_InOut.h5 file). 
thanks in advance.

P.S> Above mentioned links are invalid now.

**Comment by TolicWang** [comment]
Please provide your email address.

**Comment by TolicWang** [comment]
> Thank you very much for sharing the thesis code.
> WIll you please share the TaxiBJ dataset and also BJ13_M32x32_T30_InOut.h5 file).
> thanks in advance.
> 
> P.S> Above mentioned links are invalid now.

Please provide your email address.

**Comment by basharathussain** [comment]
> > Thank you very much for sharing the thesis code.
> > WIll you please share the TaxiBJ dataset and also BJ13_M32x32_T30_InOut.h5 file).
> > thanks in advance.
> > P.S> Above mentioned links are invalid now.
> 
> Please provide your email address.

basharat@live.com

**Comment by Woutah** [comment]
Hi, could you send me the TaxiBJ datasets as well? I am from Europe so I cannot download from the provided Baidu link. My e-mail address is: s2025418@vuw.leidenuniv.nl. Thanks in advance! 

Kind regards, Wouter

**Comment by GuptaSonam** [comment]
Can someone share the data with me too? the above links are not working. Please use my email id cs18d005@cse.iitm.ac.in

**Comment by nbasyl** [comment]
樓主你好，能麻煩您提供我TaxiBJ的 dataset嗎，非常感謝. Email: sliuau@connect.ust.hk

**Comment by LincanLi-X** [comment]
感谢，终于找到TaxiBJ dataset了，找了好久。最后一个百度网盘链接还是有效的。

**Comment by TolicWang** [comment]
> 感谢，终于找到TaxiBJ dataset了，找了好久。最后一个百度网盘链接还是有效的。

不客气

**Comment by anilkamat** [comment]
The link for data of OneDrive is broke or expired. Can you please share the data with me on alvinanil69@gmail.com.
Thanks,

**Comment by 748919551** [comment]
博主您好，请问可以发一份数据集链接吗？748919551@qq.com

**Comment by TolicWang** [comment]
> 博主您好，请问可以发一份数据集链接吗？[748919551@qq.com](mailto:748919551@qq.com)

关注 公众号 月来客栈 获取

**Comment by luooyoong** [comment]
谢谢楼主哦~~~非常棒~~~

**Comment by hayaldeniz** [comment]
Dear research team, could you also please provide me the Beijing taxi dataset. The links shared above are not working for me. Thank you! My e-mail address is: hayal.d.ozer@gmail.com

**Comment by Anuj472** [comment]
Dear research team, could you also please provide me the Beijing taxi dataset. The links shared above are not working for me. Thank you! My e-mail address is: 1908390100020@reck.ac.in

**Comment by s2499kumar** [comment]
Dear research team, could you please provide me the Beijing taxi dataset and also BJ13_M32x32_T30_InOut.h5 file, BJ14_M32x32_T30_InOut.h5 file. Thank you in advance, my mail address is shailendra9905kr@gmail.com

**Comment by mcogoni** [comment]
Dear research team, could you also please provide me the Beijing taxi dataset. The links shared above are not working for me. Thank you! My e-mail address is: [cogoni@gmail.com](mailto:cogoni@gmail.com)

**Comment by samkml** [comment]
Hi research team,
Could you please provide me the TaxiBj data folder, as I could not download the data from link.
Here is my email address :  kamel.samira1987@gmail.com

Thanks so much

**Comment by samkml** [comment]
> 链接: https://pan.baidu.com/s/1xRNv9GXvJH6WMXTaPtJcpw 提取码: vr9x

Hi,

Could you kindly provide the data through my email address? I'd appreciate it, Thanks!
kamel.samira1987@gmail.com

**Comment by Manudpb** [comment]
Hello,

None of the links above are properly working for me, can you send the data to my email address? Thanks in advance!
mdpbelizon@gmail.com

**Comment by amstudnet** [comment]
Hello,research team,
I do not have a Baidu account. Would it be possible for you to kindly send the taxibj data to my email? I would greatly appreciate it. Thank you very much.
[henry901130@yahoo.com.tw](henry901130@yahoo.com.tw)

**Comment by Hq-Zou** [comment]
Hi,
The links above are not working for me, can you send the raw data to my email address? I'd appreciate it, Thanks!
937554784@qq.com

**Comment by QingmeiLi** [comment]
Hi,
The links above are not working for me, can you send the raw data to my email address? I'd appreciate it, Thanks!
qmli@stu.pku.edu.cn

**Comment by M-Mx-M** [comment]
您好，
上面的链接对我不起作用，您可以将原始数据发送到我的电子邮件地址吗？我将不胜感激，谢谢！
2723502092@qq.com

**Comment by huangxiaoyan611** [comment]
您好，博主，请问可以再发一下BJTaxi数据集的链接吗？我的邮箱是2257231394@qq.com。非常感谢，祝您学业和工作都顺利！
